"""Add realtime_weather_id to post table

Revision ID: 1db71098cc95
Revises: 
Create Date: 2024-10-16 20:13:28.491646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1db71098cc95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_Weather')
    op.drop_table('aily_Weather')
    op.drop_table('Daily_Weather')
    with op.batch_alter_table('daily_weather', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=30),
               nullable=False)
        batch_op.drop_column('wind_speed')
        batch_op.drop_column('date')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('realtime_weather_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('post_weekly_weather_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('post_daily_weather_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'realtime_weather', ['realtime_weather_id'], ['id'])
        batch_op.drop_column('daily_weather_id')
        batch_op.drop_column('weekly_weather_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekly_weather_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('daily_weather_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_daily_weather_id_fkey', 'daily_weather', ['daily_weather_id'], ['id'])
        batch_op.create_foreign_key('post_weekly_weather_id_fkey', 'weekly_weather', ['weekly_weather_id'], ['id'])
        batch_op.drop_column('realtime_weather_id')

    with op.batch_alter_table('daily_weather', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('wind_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.alter_column('time',
               existing_type=sa.String(length=30),
               type_=postgresql.TIMESTAMP(),
               nullable=True)

    op.create_table('Daily_Weather',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temperatureApparent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('precipitationProbability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cloudCover', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('uvIndex', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('wind_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weekly_weather_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['weekly_weather_id'], ['weekly_weather.id'], name='Daily_Weather_weekly_weather_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Daily_Weather_pkey')
    )
    op.create_table('aily_Weather',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('location_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temperatureApparent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('precipitationProbability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cloudCover', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('uvIndex', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('wind_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weekly_weather_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['weekly_weather_id'], ['weekly_weather.id'], name='aily_Weather_weekly_weather_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='aily_Weather_pkey')
    )
    op.create_table('daily_Weather',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('location_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temperatureApparent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('precipitationProbability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cloudCover', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('uvIndex', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('wind_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weekly_weather_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['weekly_weather_id'], ['weekly_weather.id'], name='daily_Weather_weekly_weather_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='daily_Weather_pkey')
    )
    # ### end Alembic commands ###
